### ISSUE TITLE
How to handle delete the Remix-y way

### ISSUE THREAD

**Issue by mihalik** [jaruesink/remix-playground#1]
I enjoyed your talk this week.  Here's how I would handle delete in Remix.  Feel free to close this issue because it is not a real issue, just an easy way to add a comment.

Make both buttons `type=submit` and add a name and value.
```
          <SubmitButton name="_method" value="save" className='w-[200px]'>Save Theme</SubmitButton>
          <SubmitButton name="_method" value="delete">
            <TrashIcon />
          </SubmitButton>
```

Then, in your action:
```
if (formData.get("_method") === "save") {
    // Your save code here
} else if (formData.get("_method") === "delete") {
   // Your delete code here
}
```

Then you can delete your delete click handler and the other route.  It'll just use the standard HTML form submission.

Also, you can also support multiple forms on a single page.  I prefer to use `remix-utils` named actions for this but there is nothing magic about it really.

Update your `ThemeForm` to post back to the current page:

```
<Form method="post" action="?/addTheme" className='flex flex-col gap-2'>
```

Similarly, update the `dynamic-themes.tsx` form to with a name

```
<Form
        className='mb-8 flex flex-col gap-2'
        action='?/changeTheme'
        method='POST'
      >
```

Then you can update the action in `dynamic-themes.tsx` to handle those named actions

```
import { namedAction } from "remix-utils";

...

export async function action({ request }: ActionArgs) {
  const prisma = new PrismaClient();
  const formData = await request.formData();
  return namedAction(request, {
    async addTheme() {
      // do create
    },
    async changeTheme() {
        if (formData.get("_method") === "save") {
            // Your save code here
        } else if (formData.get("_method") === "delete") {
           // Your delete code here
        }
    }
```

Named actions are great if you want to re-use the same form on multiple pages as well.  Like if there were multiple pages where you could add a theme.  You would pop your action into `/app/services` or `/app/actions`, import it and then `return namedActions(request, {addTheme});`.

**Comment by jaruesink** [comment]
Hey @mihalik, I was busy and went to Remix Conf and just now saw that you had wrote this issue. Thanks so much for taking the time to write it!

Someone during the talk recommended that I could just listen for the form method and basically do the same thing as you had had in your example. Having the action in the same page as the code seems to be what I needed to make sure the data was flowing correctly rather than in a resource route.

It didn't work live on my talk, but when I sat back down later and spun it back up it worked as expected! I'm sure I could DRY it up a bit, but I think it's good enough for my playground.

We're currently working on utilizing defer and suspense to optimize page loading to lazy load things like product lists and search results on our pages. 🤯

```
export async function action({ request }: ActionArgs) {
  const prisma = new PrismaClient();
  const formData = await request.formData();
  const data = formDataToObject(formData) as {
    themeId: string;
  };
  const { themeId } = data;

  if (request.method === 'DELETE') {
    const theme = await prisma.theme.delete({
      where: { id: parseInt(themeId) },
    });

    const siteSettings = await prisma.siteSettings.findUnique({
      where: { id: 1 },
    });

    return json({ siteSettings });
  }

  const siteSettings = await prisma.siteSettings.update({
    where: { id: 1 },
    data: {
      themeId: parseInt(themeId),
    },
  });

  return json({ siteSettings });
}
```
